<?php
// tests/cases/legacy-drift-snapshot.php
//
// Step5-A: 「現行STG上のshichu.php/seiza.php（生きているブラウザJS）」から
// 2026-07-06にプレビューブラウザ経由で直接抽出した値。
//
// tests/cases/shichu-golden.php・seiza-golden.php（Step1凍結スナップショット）とは
// 目的が異なる: あちらは「移植時点の正しさ」の恒久的な回帰防止用、
// こちらは「本番反映直前、今のライブページとsanseiEngineが一致しているか」の
// 一度限りのドリフト検知用。
//
// ケース選定方針:
//   - shichu: tests/tools/export-shichu-golden.js の FIXED_CASES（20件）をそのまま流用。
//     Step1で既に選定済みの境界値（閏年3世代・世紀またぎ・子の刻境界・節入り前後・範囲上下限）を再利用し、
//     ゼロから設計し直さない。
//   - seiza: seiza.php の getZodiacIndex 実装（CUTOFF配列）から導出した
//     12星座切り替わり境界（前後）+ wrap確認2件 + timeZoneCode全5種。
//     境界差分は事前にNode.jsで12/12件とも検証済み。
//
// 抽出方法: ローカルPHPビルトインサーバー上でshichu.php/seiza.phpをブラウザで開き、
// window.getYearPillar 等（トップレベル関数宣言はグローバルスコープに乗る）を
// preview_eval経由で直接呼び出して取得。DOM描画やHTML文字列のパースは経由していない。
//
// 比較対象（固定）:
//   shichu raw: yearPillar/monthPillar/dayPillar/hourPillar/dayStrength/tenGodGrid/tenchusatsuBranches/daiyun
//   seiza raw : signIndex/innerTypeIndex/timeZoneIndex
//   対象外: scores/influence/archetype/extras（legacyに実体がないため比較しない）
//
// 生成元: 手動抽出（tests/tools/export-shichu-golden.js のような自動再生成スクリプトはない。
// 再実行する場合はIMPLEMENTATION_PLAN.md Step5-Aの手順を参照し、同じ入力リストで再抽出すること）

return [
    'generatedAt' => '2026-07-06',
    'generator' => 'test.life-fun.net/shichu.php, seiza.php (live browser JS, via Claude Preview eval)',

    'shichu' => [
        ['input' => ['year'=>1990,'month'=>1,'day'=>1,'hour'=>null,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>5,'branch'=>5],'monthPillar'=>['stem'=>2,'branch'=>0],'dayPillar'=>['stem'=>2,'branch'=>2],'hourPillar'=>null,'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>5,'tenGodIndex'=>3],['label'=>'年支（蔵干）','stem'=>2,'tenGodIndex'=>0],['label'=>'月干','stem'=>2,'tenGodIndex'=>0],['label'=>'月支（蔵干）','stem'=>8,'tenGodIndex'=>6],['label'=>'日支（蔵干）','stem'=>0,'tenGodIndex'=>8]],'tenchusatsuBranches'=>[10,11],'daiyun'=>['forward'=>false,'startAge'=>8,'periods'=>[['stem'=>1,'branch'=>11,'startAge'=>8,'tenGodIndex'=>9,'juniName'=>'絶'],['stem'=>0,'branch'=>10,'startAge'=>18,'tenGodIndex'=>8,'juniName'=>'墓'],['stem'=>9,'branch'=>9,'startAge'=>28,'tenGodIndex'=>7,'juniName'=>'死'],['stem'=>8,'branch'=>8,'startAge'=>38,'tenGodIndex'=>6,'juniName'=>'病'],['stem'=>7,'branch'=>7,'startAge'=>48,'tenGodIndex'=>5,'juniName'=>'衰'],['stem'=>6,'branch'=>6,'startAge'=>58,'tenGodIndex'=>4,'juniName'=>'帝旺'],['stem'=>5,'branch'=>5,'startAge'=>68,'tenGodIndex'=>3,'juniName'=>'建禄'],['stem'=>4,'branch'=>4,'startAge'=>78,'tenGodIndex'=>2,'juniName'=>'冠帯']]]]],
        ['input' => ['year'=>1990,'month'=>1,'day'=>5,'hour'=>10,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>5,'branch'=>5],'monthPillar'=>['stem'=>2,'branch'=>0],'dayPillar'=>['stem'=>6,'branch'=>6],'hourPillar'=>['stem'=>7,'branch'=>5],'dayStrength'=>['label'=>'中和','cls'=>'strength-mid','desc'=>'バランスが取れた命式。柔軟な対応が強み。'],'tenGodGrid'=>[['label'=>'年干','stem'=>5,'tenGodIndex'=>9],['label'=>'年支（蔵干）','stem'=>2,'tenGodIndex'=>6],['label'=>'月干','stem'=>2,'tenGodIndex'=>6],['label'=>'月支（蔵干）','stem'=>8,'tenGodIndex'=>2],['label'=>'日支（蔵干）','stem'=>3,'tenGodIndex'=>7],['label'=>'時干','stem'=>7,'tenGodIndex'=>1],['label'=>'時支（蔵干）','stem'=>2,'tenGodIndex'=>6]],'tenchusatsuBranches'=>[10,11],'daiyun'=>['forward'=>true,'startAge'=>0,'periods'=>[['stem'=>3,'branch'=>1,'startAge'=>0,'tenGodIndex'=>7,'juniName'=>'墓'],['stem'=>4,'branch'=>2,'startAge'=>10,'tenGodIndex'=>8,'juniName'=>'絶'],['stem'=>5,'branch'=>3,'startAge'=>20,'tenGodIndex'=>9,'juniName'=>'胎'],['stem'=>6,'branch'=>4,'startAge'=>30,'tenGodIndex'=>0,'juniName'=>'養'],['stem'=>7,'branch'=>5,'startAge'=>40,'tenGodIndex'=>1,'juniName'=>'長生'],['stem'=>8,'branch'=>6,'startAge'=>50,'tenGodIndex'=>2,'juniName'=>'沐浴'],['stem'=>9,'branch'=>7,'startAge'=>60,'tenGodIndex'=>3,'juniName'=>'冠帯'],['stem'=>0,'branch'=>8,'startAge'=>70,'tenGodIndex'=>4,'juniName'=>'建禄']]]]],
        ['input' => ['year'=>1988,'month'=>2,'day'=>3,'hour'=>23,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>3,'branch'=>3],'monthPillar'=>['stem'=>1,'branch'=>1],'dayPillar'=>['stem'=>4,'branch'=>0],'hourPillar'=>['stem'=>8,'branch'=>0],'dayStrength'=>['label'=>'中和','cls'=>'strength-mid','desc'=>'バランスが取れた命式。柔軟な対応が強み。'],'tenGodGrid'=>[['label'=>'年干','stem'=>3,'tenGodIndex'=>9],['label'=>'年支（蔵干）','stem'=>1,'tenGodIndex'=>7],['label'=>'月干','stem'=>1,'tenGodIndex'=>7],['label'=>'月支（蔵干）','stem'=>5,'tenGodIndex'=>1],['label'=>'日支（蔵干）','stem'=>8,'tenGodIndex'=>4],['label'=>'時干','stem'=>8,'tenGodIndex'=>4],['label'=>'時支（蔵干）','stem'=>8,'tenGodIndex'=>4]],'tenchusatsuBranches'=>[6,7],'daiyun'=>['forward'=>false,'startAge'=>9,'periods'=>[['stem'=>0,'branch'=>0,'startAge'=>9,'tenGodIndex'=>6,'juniName'=>'胎'],['stem'=>9,'branch'=>11,'startAge'=>19,'tenGodIndex'=>5,'juniName'=>'絶'],['stem'=>8,'branch'=>10,'startAge'=>29,'tenGodIndex'=>4,'juniName'=>'墓'],['stem'=>7,'branch'=>9,'startAge'=>39,'tenGodIndex'=>3,'juniName'=>'死'],['stem'=>6,'branch'=>8,'startAge'=>49,'tenGodIndex'=>2,'juniName'=>'病'],['stem'=>5,'branch'=>7,'startAge'=>59,'tenGodIndex'=>1,'juniName'=>'衰'],['stem'=>4,'branch'=>6,'startAge'=>69,'tenGodIndex'=>0,'juniName'=>'帝旺'],['stem'=>3,'branch'=>5,'startAge'=>79,'tenGodIndex'=>9,'juniName'=>'建禄']]]]],
        ['input' => ['year'=>1988,'month'=>2,'day'=>5,'hour'=>0,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>4,'branch'=>4],'monthPillar'=>['stem'=>0,'branch'=>2],'dayPillar'=>['stem'=>6,'branch'=>2],'hourPillar'=>['stem'=>2,'branch'=>0],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>4,'tenGodIndex'=>8],['label'=>'年支（蔵干）','stem'=>4,'tenGodIndex'=>8],['label'=>'月干','stem'=>0,'tenGodIndex'=>4],['label'=>'月支（蔵干）','stem'=>0,'tenGodIndex'=>4],['label'=>'日支（蔵干）','stem'=>0,'tenGodIndex'=>4],['label'=>'時干','stem'=>2,'tenGodIndex'=>6],['label'=>'時支（蔵干）','stem'=>8,'tenGodIndex'=>2]],'tenchusatsuBranches'=>[6,7],'daiyun'=>['forward'=>false,'startAge'=>0,'periods'=>[['stem'=>9,'branch'=>1,'startAge'=>0,'tenGodIndex'=>3,'juniName'=>'墓'],['stem'=>8,'branch'=>0,'startAge'=>10,'tenGodIndex'=>2,'juniName'=>'死'],['stem'=>7,'branch'=>11,'startAge'=>20,'tenGodIndex'=>1,'juniName'=>'病'],['stem'=>6,'branch'=>10,'startAge'=>30,'tenGodIndex'=>0,'juniName'=>'衰'],['stem'=>5,'branch'=>9,'startAge'=>40,'tenGodIndex'=>9,'juniName'=>'帝旺'],['stem'=>4,'branch'=>8,'startAge'=>50,'tenGodIndex'=>8,'juniName'=>'建禄'],['stem'=>3,'branch'=>7,'startAge'=>60,'tenGodIndex'=>7,'juniName'=>'冠帯'],['stem'=>2,'branch'=>6,'startAge'=>70,'tenGodIndex'=>6,'juniName'=>'沐浴']]]]],
        ['input' => ['year'=>2000,'month'=>2,'day'=>29,'hour'=>12,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>6,'branch'=>4],'monthPillar'=>['stem'=>4,'branch'=>2],'dayPillar'=>['stem'=>3,'branch'=>5],'hourPillar'=>['stem'=>2,'branch'=>6],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>6,'tenGodIndex'=>5],['label'=>'年支（蔵干）','stem'=>4,'tenGodIndex'=>3],['label'=>'月干','stem'=>4,'tenGodIndex'=>3],['label'=>'月支（蔵干）','stem'=>0,'tenGodIndex'=>9],['label'=>'日支（蔵干）','stem'=>2,'tenGodIndex'=>1],['label'=>'時干','stem'=>2,'tenGodIndex'=>1],['label'=>'時支（蔵干）','stem'=>3,'tenGodIndex'=>0]],'tenchusatsuBranches'=>[0,1],'daiyun'=>['forward'=>true,'startAge'=>2,'periods'=>[['stem'=>5,'branch'=>3,'startAge'=>2,'tenGodIndex'=>2,'juniName'=>'病'],['stem'=>6,'branch'=>4,'startAge'=>12,'tenGodIndex'=>5,'juniName'=>'衰'],['stem'=>7,'branch'=>5,'startAge'=>22,'tenGodIndex'=>4,'juniName'=>'帝旺'],['stem'=>8,'branch'=>6,'startAge'=>32,'tenGodIndex'=>7,'juniName'=>'建禄'],['stem'=>9,'branch'=>7,'startAge'=>42,'tenGodIndex'=>6,'juniName'=>'冠帯'],['stem'=>0,'branch'=>8,'startAge'=>52,'tenGodIndex'=>9,'juniName'=>'沐浴'],['stem'=>1,'branch'=>9,'startAge'=>62,'tenGodIndex'=>8,'juniName'=>'長生'],['stem'=>2,'branch'=>10,'startAge'=>72,'tenGodIndex'=>1,'juniName'=>'養']]]]],
        ['input' => ['year'=>1996,'month'=>2,'day'=>29,'hour'=>6,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>2,'branch'=>0],'monthPillar'=>['stem'=>6,'branch'=>2],'dayPillar'=>['stem'=>2,'branch'=>8],'hourPillar'=>['stem'=>7,'branch'=>3],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>2,'tenGodIndex'=>0],['label'=>'年支（蔵干）','stem'=>8,'tenGodIndex'=>6],['label'=>'月干','stem'=>6,'tenGodIndex'=>4],['label'=>'月支（蔵干）','stem'=>0,'tenGodIndex'=>8],['label'=>'日支（蔵干）','stem'=>6,'tenGodIndex'=>4],['label'=>'時干','stem'=>7,'tenGodIndex'=>5],['label'=>'時支（蔵干）','stem'=>1,'tenGodIndex'=>9]],'tenchusatsuBranches'=>[4,5],'daiyun'=>['forward'=>false,'startAge'=>8,'periods'=>[['stem'=>5,'branch'=>1,'startAge'=>8,'tenGodIndex'=>3,'juniName'=>'養'],['stem'=>4,'branch'=>0,'startAge'=>18,'tenGodIndex'=>2,'juniName'=>'胎'],['stem'=>3,'branch'=>11,'startAge'=>28,'tenGodIndex'=>1,'juniName'=>'絶'],['stem'=>2,'branch'=>10,'startAge'=>38,'tenGodIndex'=>0,'juniName'=>'墓'],['stem'=>1,'branch'=>9,'startAge'=>48,'tenGodIndex'=>9,'juniName'=>'死'],['stem'=>0,'branch'=>8,'startAge'=>58,'tenGodIndex'=>8,'juniName'=>'病'],['stem'=>9,'branch'=>7,'startAge'=>68,'tenGodIndex'=>7,'juniName'=>'衰'],['stem'=>8,'branch'=>6,'startAge'=>78,'tenGodIndex'=>6,'juniName'=>'帝旺']]]]],
        ['input' => ['year'=>2024,'month'=>2,'day'=>29,'hour'=>18,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>0,'branch'=>4],'monthPillar'=>['stem'=>2,'branch'=>2],'dayPillar'=>['stem'=>9,'branch'=>11],'hourPillar'=>['stem'=>7,'branch'=>9],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>0,'tenGodIndex'=>3],['label'=>'年支（蔵干）','stem'=>4,'tenGodIndex'=>7],['label'=>'月干','stem'=>2,'tenGodIndex'=>5],['label'=>'月支（蔵干）','stem'=>0,'tenGodIndex'=>3],['label'=>'日支（蔵干）','stem'=>8,'tenGodIndex'=>1],['label'=>'時干','stem'=>7,'tenGodIndex'=>8],['label'=>'時支（蔵干）','stem'=>7,'tenGodIndex'=>8]],'tenchusatsuBranches'=>[0,1],'daiyun'=>['forward'=>true,'startAge'=>2,'periods'=>[['stem'=>3,'branch'=>3,'startAge'=>2,'tenGodIndex'=>4,'juniName'=>'長生'],['stem'=>4,'branch'=>4,'startAge'=>12,'tenGodIndex'=>7,'juniName'=>'養'],['stem'=>5,'branch'=>5,'startAge'=>22,'tenGodIndex'=>6,'juniName'=>'胎'],['stem'=>6,'branch'=>6,'startAge'=>32,'tenGodIndex'=>9,'juniName'=>'絶'],['stem'=>7,'branch'=>7,'startAge'=>42,'tenGodIndex'=>8,'juniName'=>'墓'],['stem'=>8,'branch'=>8,'startAge'=>52,'tenGodIndex'=>1,'juniName'=>'死'],['stem'=>9,'branch'=>9,'startAge'=>62,'tenGodIndex'=>0,'juniName'=>'病'],['stem'=>0,'branch'=>10,'startAge'=>72,'tenGodIndex'=>3,'juniName'=>'衰']]]]],
        ['input' => ['year'=>1985,'month'=>12,'day'=>31,'hour'=>23,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>1,'branch'=>1],'monthPillar'=>['stem'=>4,'branch'=>0],'dayPillar'=>['stem'=>0,'branch'=>4],'hourPillar'=>['stem'=>0,'branch'=>0],'dayStrength'=>['label'=>'中和','cls'=>'strength-mid','desc'=>'バランスが取れた命式。柔軟な対応が強み。'],'tenGodGrid'=>[['label'=>'年干','stem'=>1,'tenGodIndex'=>1],['label'=>'年支（蔵干）','stem'=>5,'tenGodIndex'=>5],['label'=>'月干','stem'=>4,'tenGodIndex'=>4],['label'=>'月支（蔵干）','stem'=>8,'tenGodIndex'=>8],['label'=>'日支（蔵干）','stem'=>4,'tenGodIndex'=>4],['label'=>'時干','stem'=>0,'tenGodIndex'=>0],['label'=>'時支（蔵干）','stem'=>8,'tenGodIndex'=>8]],'tenchusatsuBranches'=>[2,3],'daiyun'=>['forward'=>true,'startAge'=>2,'periods'=>[['stem'=>5,'branch'=>1,'startAge'=>2,'tenGodIndex'=>5,'juniName'=>'冠帯'],['stem'=>6,'branch'=>2,'startAge'=>12,'tenGodIndex'=>6,'juniName'=>'建禄'],['stem'=>7,'branch'=>3,'startAge'=>22,'tenGodIndex'=>7,'juniName'=>'帝旺'],['stem'=>8,'branch'=>4,'startAge'=>32,'tenGodIndex'=>8,'juniName'=>'衰'],['stem'=>9,'branch'=>5,'startAge'=>42,'tenGodIndex'=>9,'juniName'=>'病'],['stem'=>0,'branch'=>6,'startAge'=>52,'tenGodIndex'=>0,'juniName'=>'死'],['stem'=>1,'branch'=>7,'startAge'=>62,'tenGodIndex'=>1,'juniName'=>'墓'],['stem'=>2,'branch'=>8,'startAge'=>72,'tenGodIndex'=>2,'juniName'=>'絶']]]]],
        ['input' => ['year'=>1999,'month'=>12,'day'=>31,'hour'=>0,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>5,'branch'=>3],'monthPillar'=>['stem'=>2,'branch'=>0],'dayPillar'=>['stem'=>3,'branch'=>5],'hourPillar'=>['stem'=>6,'branch'=>0],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>5,'tenGodIndex'=>2],['label'=>'年支（蔵干）','stem'=>1,'tenGodIndex'=>8],['label'=>'月干','stem'=>2,'tenGodIndex'=>1],['label'=>'月支（蔵干）','stem'=>8,'tenGodIndex'=>7],['label'=>'日支（蔵干）','stem'=>2,'tenGodIndex'=>1],['label'=>'時干','stem'=>6,'tenGodIndex'=>5],['label'=>'時支（蔵干）','stem'=>8,'tenGodIndex'=>7]],'tenchusatsuBranches'=>[0,1],'daiyun'=>['forward'=>false,'startAge'=>8,'periods'=>[['stem'=>1,'branch'=>11,'startAge'=>8,'tenGodIndex'=>8,'juniName'=>'胎'],['stem'=>0,'branch'=>10,'startAge'=>18,'tenGodIndex'=>9,'juniName'=>'養'],['stem'=>9,'branch'=>9,'startAge'=>28,'tenGodIndex'=>6,'juniName'=>'長生'],['stem'=>8,'branch'=>8,'startAge'=>38,'tenGodIndex'=>7,'juniName'=>'沐浴'],['stem'=>7,'branch'=>7,'startAge'=>48,'tenGodIndex'=>4,'juniName'=>'冠帯'],['stem'=>6,'branch'=>6,'startAge'=>58,'tenGodIndex'=>5,'juniName'=>'建禄'],['stem'=>5,'branch'=>5,'startAge'=>68,'tenGodIndex'=>2,'juniName'=>'帝旺'],['stem'=>4,'branch'=>4,'startAge'=>78,'tenGodIndex'=>3,'juniName'=>'衰']]]]],
        ['input' => ['year'=>2000,'month'=>1,'day'=>1,'hour'=>1,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>5,'branch'=>3],'monthPillar'=>['stem'=>2,'branch'=>0],'dayPillar'=>['stem'=>4,'branch'=>6],'hourPillar'=>['stem'=>9,'branch'=>1],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>5,'tenGodIndex'=>1],['label'=>'年支（蔵干）','stem'=>1,'tenGodIndex'=>7],['label'=>'月干','stem'=>2,'tenGodIndex'=>8],['label'=>'月支（蔵干）','stem'=>8,'tenGodIndex'=>4],['label'=>'日支（蔵干）','stem'=>3,'tenGodIndex'=>9],['label'=>'時干','stem'=>9,'tenGodIndex'=>5],['label'=>'時支（蔵干）','stem'=>5,'tenGodIndex'=>1]],'tenchusatsuBranches'=>[0,1],'daiyun'=>['forward'=>true,'startAge'=>1,'periods'=>[['stem'=>3,'branch'=>1,'startAge'=>1,'tenGodIndex'=>9,'juniName'=>'養'],['stem'=>4,'branch'=>2,'startAge'=>11,'tenGodIndex'=>0,'juniName'=>'長生'],['stem'=>5,'branch'=>3,'startAge'=>21,'tenGodIndex'=>1,'juniName'=>'沐浴'],['stem'=>6,'branch'=>4,'startAge'=>31,'tenGodIndex'=>2,'juniName'=>'冠帯'],['stem'=>7,'branch'=>5,'startAge'=>41,'tenGodIndex'=>3,'juniName'=>'建禄'],['stem'=>8,'branch'=>6,'startAge'=>51,'tenGodIndex'=>4,'juniName'=>'帝旺'],['stem'=>9,'branch'=>7,'startAge'=>61,'tenGodIndex'=>5,'juniName'=>'衰'],['stem'=>0,'branch'=>8,'startAge'=>71,'tenGodIndex'=>6,'juniName'=>'病']]]]],
        ['input' => ['year'=>1975,'month'=>6,'day'=>15,'hour'=>null,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>1,'branch'=>3],'monthPillar'=>['stem'=>8,'branch'=>6],'dayPillar'=>['stem'=>8,'branch'=>4],'hourPillar'=>null,'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>1,'tenGodIndex'=>3],['label'=>'年支（蔵干）','stem'=>1,'tenGodIndex'=>3],['label'=>'月干','stem'=>8,'tenGodIndex'=>0],['label'=>'月支（蔵干）','stem'=>3,'tenGodIndex'=>5],['label'=>'日支（蔵干）','stem'=>4,'tenGodIndex'=>6]],'tenchusatsuBranches'=>[6,7],'daiyun'=>['forward'=>false,'startAge'=>3,'periods'=>[['stem'=>7,'branch'=>5,'startAge'=>3,'tenGodIndex'=>9,'juniName'=>'絶'],['stem'=>6,'branch'=>4,'startAge'=>13,'tenGodIndex'=>8,'juniName'=>'墓'],['stem'=>5,'branch'=>3,'startAge'=>23,'tenGodIndex'=>7,'juniName'=>'死'],['stem'=>4,'branch'=>2,'startAge'=>33,'tenGodIndex'=>6,'juniName'=>'病'],['stem'=>3,'branch'=>1,'startAge'=>43,'tenGodIndex'=>5,'juniName'=>'衰'],['stem'=>2,'branch'=>0,'startAge'=>53,'tenGodIndex'=>4,'juniName'=>'帝旺'],['stem'=>1,'branch'=>11,'startAge'=>63,'tenGodIndex'=>3,'juniName'=>'建禄'],['stem'=>0,'branch'=>10,'startAge'=>73,'tenGodIndex'=>2,'juniName'=>'冠帯']]]]],
        ['input' => ['year'=>1982,'month'=>7,'day'=>20,'hour'=>14,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>8,'branch'=>10],'monthPillar'=>['stem'=>3,'branch'=>7],'dayPillar'=>['stem'=>0,'branch'=>4],'hourPillar'=>['stem'=>7,'branch'=>7],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>8,'tenGodIndex'=>8],['label'=>'年支（蔵干）','stem'=>4,'tenGodIndex'=>4],['label'=>'月干','stem'=>3,'tenGodIndex'=>3],['label'=>'月支（蔵干）','stem'=>5,'tenGodIndex'=>5],['label'=>'日支（蔵干）','stem'=>4,'tenGodIndex'=>4],['label'=>'時干','stem'=>7,'tenGodIndex'=>7],['label'=>'時支（蔵干）','stem'=>5,'tenGodIndex'=>5]],'tenchusatsuBranches'=>[2,3],'daiyun'=>['forward'=>false,'startAge'=>4,'periods'=>[['stem'=>2,'branch'=>6,'startAge'=>4,'tenGodIndex'=>2,'juniName'=>'死'],['stem'=>1,'branch'=>5,'startAge'=>14,'tenGodIndex'=>1,'juniName'=>'病'],['stem'=>0,'branch'=>4,'startAge'=>24,'tenGodIndex'=>0,'juniName'=>'衰'],['stem'=>9,'branch'=>3,'startAge'=>34,'tenGodIndex'=>9,'juniName'=>'帝旺'],['stem'=>8,'branch'=>2,'startAge'=>44,'tenGodIndex'=>8,'juniName'=>'建禄'],['stem'=>7,'branch'=>1,'startAge'=>54,'tenGodIndex'=>7,'juniName'=>'冠帯'],['stem'=>6,'branch'=>0,'startAge'=>64,'tenGodIndex'=>6,'juniName'=>'沐浴'],['stem'=>5,'branch'=>11,'startAge'=>74,'tenGodIndex'=>5,'juniName'=>'長生']]]]],
        ['input' => ['year'=>1960,'month'=>3,'day'=>5,'hour'=>3,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>6,'branch'=>0],'monthPillar'=>['stem'=>4,'branch'=>2],'dayPillar'=>['stem'=>8,'branch'=>4],'hourPillar'=>['stem'=>8,'branch'=>2],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>6,'tenGodIndex'=>8],['label'=>'年支（蔵干）','stem'=>8,'tenGodIndex'=>0],['label'=>'月干','stem'=>4,'tenGodIndex'=>6],['label'=>'月支（蔵干）','stem'=>0,'tenGodIndex'=>2],['label'=>'日支（蔵干）','stem'=>4,'tenGodIndex'=>6],['label'=>'時干','stem'=>8,'tenGodIndex'=>0],['label'=>'時支（蔵干）','stem'=>0,'tenGodIndex'=>2]],'tenchusatsuBranches'=>[6,7],'daiyun'=>['forward'=>true,'startAge'=>0,'periods'=>[['stem'=>5,'branch'=>3,'startAge'=>0,'tenGodIndex'=>7,'juniName'=>'死'],['stem'=>6,'branch'=>4,'startAge'=>10,'tenGodIndex'=>8,'juniName'=>'墓'],['stem'=>7,'branch'=>5,'startAge'=>20,'tenGodIndex'=>9,'juniName'=>'絶'],['stem'=>8,'branch'=>6,'startAge'=>30,'tenGodIndex'=>0,'juniName'=>'胎'],['stem'=>9,'branch'=>7,'startAge'=>40,'tenGodIndex'=>1,'juniName'=>'養'],['stem'=>0,'branch'=>8,'startAge'=>50,'tenGodIndex'=>2,'juniName'=>'長生'],['stem'=>1,'branch'=>9,'startAge'=>60,'tenGodIndex'=>3,'juniName'=>'沐浴'],['stem'=>2,'branch'=>10,'startAge'=>70,'tenGodIndex'=>4,'juniName'=>'冠帯']]]]],
        ['input' => ['year'=>2010,'month'=>4,'day'=>4,'hour'=>9,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>6,'branch'=>2],'monthPillar'=>['stem'=>5,'branch'=>3],'dayPillar'=>['stem'=>0,'branch'=>8],'hourPillar'=>['stem'=>5,'branch'=>5],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>6,'tenGodIndex'=>6],['label'=>'年支（蔵干）','stem'=>0,'tenGodIndex'=>0],['label'=>'月干','stem'=>5,'tenGodIndex'=>5],['label'=>'月支（蔵干）','stem'=>1,'tenGodIndex'=>1],['label'=>'日支（蔵干）','stem'=>6,'tenGodIndex'=>6],['label'=>'時干','stem'=>5,'tenGodIndex'=>5],['label'=>'時支（蔵干）','stem'=>2,'tenGodIndex'=>2]],'tenchusatsuBranches'=>[6,7],'daiyun'=>['forward'=>false,'startAge'=>10,'periods'=>[['stem'=>4,'branch'=>2,'startAge'=>10,'tenGodIndex'=>4,'juniName'=>'建禄'],['stem'=>3,'branch'=>1,'startAge'=>20,'tenGodIndex'=>3,'juniName'=>'冠帯'],['stem'=>2,'branch'=>0,'startAge'=>30,'tenGodIndex'=>2,'juniName'=>'沐浴'],['stem'=>1,'branch'=>11,'startAge'=>40,'tenGodIndex'=>1,'juniName'=>'長生'],['stem'=>0,'branch'=>10,'startAge'=>50,'tenGodIndex'=>0,'juniName'=>'養'],['stem'=>9,'branch'=>9,'startAge'=>60,'tenGodIndex'=>9,'juniName'=>'胎'],['stem'=>8,'branch'=>8,'startAge'=>70,'tenGodIndex'=>8,'juniName'=>'絶'],['stem'=>7,'branch'=>7,'startAge'=>80,'tenGodIndex'=>7,'juniName'=>'墓']]]]],
        ['input' => ['year'=>1993,'month'=>5,'day'=>5,'hour'=>21,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>9,'branch'=>9],'monthPillar'=>['stem'=>3,'branch'=>5],'dayPillar'=>['stem'=>2,'branch'=>10],'hourPillar'=>['stem'=>5,'branch'=>11],'dayStrength'=>['label'=>'中和','cls'=>'strength-mid','desc'=>'バランスが取れた命式。柔軟な対応が強み。'],'tenGodGrid'=>[['label'=>'年干','stem'=>9,'tenGodIndex'=>7],['label'=>'年支（蔵干）','stem'=>7,'tenGodIndex'=>5],['label'=>'月干','stem'=>3,'tenGodIndex'=>1],['label'=>'月支（蔵干）','stem'=>2,'tenGodIndex'=>0],['label'=>'日支（蔵干）','stem'=>4,'tenGodIndex'=>2],['label'=>'時干','stem'=>5,'tenGodIndex'=>3],['label'=>'時支（蔵干）','stem'=>8,'tenGodIndex'=>6]],'tenchusatsuBranches'=>[6,7],'daiyun'=>['forward'=>false,'startAge'=>0,'periods'=>[['stem'=>2,'branch'=>4,'startAge'=>0,'tenGodIndex'=>0,'juniName'=>'冠帯'],['stem'=>1,'branch'=>3,'startAge'=>10,'tenGodIndex'=>9,'juniName'=>'沐浴'],['stem'=>0,'branch'=>2,'startAge'=>20,'tenGodIndex'=>8,'juniName'=>'長生'],['stem'=>9,'branch'=>1,'startAge'=>30,'tenGodIndex'=>7,'juniName'=>'養'],['stem'=>8,'branch'=>0,'startAge'=>40,'tenGodIndex'=>6,'juniName'=>'胎'],['stem'=>7,'branch'=>11,'startAge'=>50,'tenGodIndex'=>5,'juniName'=>'絶'],['stem'=>6,'branch'=>10,'startAge'=>60,'tenGodIndex'=>4,'juniName'=>'墓'],['stem'=>5,'branch'=>9,'startAge'=>70,'tenGodIndex'=>3,'juniName'=>'死']]]]],
        ['input' => ['year'=>1978,'month'=>8,'day'=>7,'hour'=>15,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>4,'branch'=>6],'monthPillar'=>['stem'=>6,'branch'=>8],'dayPillar'=>['stem'=>7,'branch'=>1],'hourPillar'=>['stem'=>2,'branch'=>8],'dayStrength'=>['label'=>'中和','cls'=>'strength-mid','desc'=>'バランスが取れた命式。柔軟な対応が強み。'],'tenGodGrid'=>[['label'=>'年干','stem'=>4,'tenGodIndex'=>9],['label'=>'年支（蔵干）','stem'=>3,'tenGodIndex'=>6],['label'=>'月干','stem'=>6,'tenGodIndex'=>1],['label'=>'月支（蔵干）','stem'=>6,'tenGodIndex'=>1],['label'=>'日支（蔵干）','stem'=>5,'tenGodIndex'=>8],['label'=>'時干','stem'=>2,'tenGodIndex'=>7],['label'=>'時支（蔵干）','stem'=>6,'tenGodIndex'=>1]],'tenchusatsuBranches'=>[4,5],'daiyun'=>['forward'=>false,'startAge'=>0,'periods'=>[['stem'=>5,'branch'=>7,'startAge'=>0,'tenGodIndex'=>8,'juniName'=>'衰'],['stem'=>4,'branch'=>6,'startAge'=>10,'tenGodIndex'=>9,'juniName'=>'病'],['stem'=>3,'branch'=>5,'startAge'=>20,'tenGodIndex'=>6,'juniName'=>'死'],['stem'=>2,'branch'=>4,'startAge'=>30,'tenGodIndex'=>7,'juniName'=>'墓'],['stem'=>1,'branch'=>3,'startAge'=>40,'tenGodIndex'=>4,'juniName'=>'絶'],['stem'=>0,'branch'=>2,'startAge'=>50,'tenGodIndex'=>5,'juniName'=>'胎'],['stem'=>9,'branch'=>1,'startAge'=>60,'tenGodIndex'=>2,'juniName'=>'養'],['stem'=>8,'branch'=>0,'startAge'=>70,'tenGodIndex'=>3,'juniName'=>'長生']]]]],
        ['input' => ['year'=>2005,'month'=>11,'day'=>7,'hour'=>2,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>1,'branch'=>9],'monthPillar'=>['stem'=>3,'branch'=>11],'dayPillar'=>['stem'=>1,'branch'=>7],'hourPillar'=>['stem'=>3,'branch'=>1],'dayStrength'=>['label'=>'中和','cls'=>'strength-mid','desc'=>'バランスが取れた命式。柔軟な対応が強み。'],'tenGodGrid'=>[['label'=>'年干','stem'=>1,'tenGodIndex'=>0],['label'=>'年支（蔵干）','stem'=>7,'tenGodIndex'=>6],['label'=>'月干','stem'=>3,'tenGodIndex'=>2],['label'=>'月支（蔵干）','stem'=>8,'tenGodIndex'=>9],['label'=>'日支（蔵干）','stem'=>5,'tenGodIndex'=>4],['label'=>'時干','stem'=>3,'tenGodIndex'=>2],['label'=>'時支（蔵干）','stem'=>5,'tenGodIndex'=>4]],'tenchusatsuBranches'=>[4,5],'daiyun'=>['forward'=>false,'startAge'=>0,'periods'=>[['stem'=>2,'branch'=>10,'startAge'=>0,'tenGodIndex'=>3,'juniName'=>'墓'],['stem'=>1,'branch'=>9,'startAge'=>10,'tenGodIndex'=>0,'juniName'=>'絶'],['stem'=>0,'branch'=>8,'startAge'=>20,'tenGodIndex'=>1,'juniName'=>'胎'],['stem'=>9,'branch'=>7,'startAge'=>30,'tenGodIndex'=>8,'juniName'=>'養'],['stem'=>8,'branch'=>6,'startAge'=>40,'tenGodIndex'=>9,'juniName'=>'長生'],['stem'=>7,'branch'=>5,'startAge'=>50,'tenGodIndex'=>6,'juniName'=>'沐浴'],['stem'=>6,'branch'=>4,'startAge'=>60,'tenGodIndex'=>7,'juniName'=>'冠帯'],['stem'=>5,'branch'=>3,'startAge'=>70,'tenGodIndex'=>4,'juniName'=>'建禄']]]]],
        ['input' => ['year'=>1965,'month'=>10,'day'=>8,'hour'=>17,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>1,'branch'=>5],'monthPillar'=>['stem'=>2,'branch'=>10],'dayPillar'=>['stem'=>1,'branch'=>7],'hourPillar'=>['stem'=>1,'branch'=>9],'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>1,'tenGodIndex'=>0],['label'=>'年支（蔵干）','stem'=>2,'tenGodIndex'=>3],['label'=>'月干','stem'=>2,'tenGodIndex'=>3],['label'=>'月支（蔵干）','stem'=>4,'tenGodIndex'=>5],['label'=>'日支（蔵干）','stem'=>5,'tenGodIndex'=>4],['label'=>'時干','stem'=>1,'tenGodIndex'=>0],['label'=>'時支（蔵干）','stem'=>7,'tenGodIndex'=>6]],'tenchusatsuBranches'=>[4,5],'daiyun'=>['forward'=>true,'startAge'=>10,'periods'=>[['stem'=>3,'branch'=>11,'startAge'=>10,'tenGodIndex'=>2,'juniName'=>'死'],['stem'=>4,'branch'=>0,'startAge'=>20,'tenGodIndex'=>5,'juniName'=>'病'],['stem'=>5,'branch'=>1,'startAge'=>30,'tenGodIndex'=>4,'juniName'=>'衰'],['stem'=>6,'branch'=>2,'startAge'=>40,'tenGodIndex'=>7,'juniName'=>'帝旺'],['stem'=>7,'branch'=>3,'startAge'=>50,'tenGodIndex'=>6,'juniName'=>'建禄'],['stem'=>8,'branch'=>4,'startAge'=>60,'tenGodIndex'=>9,'juniName'=>'冠帯'],['stem'=>9,'branch'=>5,'startAge'=>70,'tenGodIndex'=>8,'juniName'=>'沐浴'],['stem'=>0,'branch'=>6,'startAge'=>80,'tenGodIndex'=>1,'juniName'=>'長生']]]]],
        ['input' => ['year'=>1900,'month'=>1,'day'=>1,'hour'=>null,'gender'=>'male'],
         'expected' => ['yearPillar'=>['stem'=>5,'branch'=>11],'monthPillar'=>['stem'=>2,'branch'=>0],'dayPillar'=>['stem'=>0,'branch'=>10],'hourPillar'=>null,'dayStrength'=>['label'=>'身弱','cls'=>'strength-weak','desc'=>'周囲のサポートを活かすことで力を発揮する。'],'tenGodGrid'=>[['label'=>'年干','stem'=>5,'tenGodIndex'=>5],['label'=>'年支（蔵干）','stem'=>8,'tenGodIndex'=>8],['label'=>'月干','stem'=>2,'tenGodIndex'=>2],['label'=>'月支（蔵干）','stem'=>8,'tenGodIndex'=>8],['label'=>'日支（蔵干）','stem'=>4,'tenGodIndex'=>4]],'tenchusatsuBranches'=>[8,9],'daiyun'=>['forward'=>false,'startAge'=>8,'periods'=>[['stem'=>1,'branch'=>11,'startAge'=>8,'tenGodIndex'=>1,'juniName'=>'長生'],['stem'=>0,'branch'=>10,'startAge'=>18,'tenGodIndex'=>0,'juniName'=>'養'],['stem'=>9,'branch'=>9,'startAge'=>28,'tenGodIndex'=>9,'juniName'=>'胎'],['stem'=>8,'branch'=>8,'startAge'=>38,'tenGodIndex'=>8,'juniName'=>'絶'],['stem'=>7,'branch'=>7,'startAge'=>48,'tenGodIndex'=>7,'juniName'=>'墓'],['stem'=>6,'branch'=>6,'startAge'=>58,'tenGodIndex'=>6,'juniName'=>'死'],['stem'=>5,'branch'=>5,'startAge'=>68,'tenGodIndex'=>5,'juniName'=>'病'],['stem'=>4,'branch'=>4,'startAge'=>78,'tenGodIndex'=>4,'juniName'=>'衰']]]]],
        ['input' => ['year'=>2099,'month'=>12,'day'=>31,'hour'=>23,'gender'=>'female'],
         'expected' => ['yearPillar'=>['stem'=>5,'branch'=>7],'monthPillar'=>['stem'=>2,'branch'=>0],'dayPillar'=>['stem'=>8,'branch'=>2],'hourPillar'=>['stem'=>6,'branch'=>0],'dayStrength'=>['label'=>'中和','cls'=>'strength-mid','desc'=>'バランスが取れた命式。柔軟な対応が強み。'],'tenGodGrid'=>[['label'=>'年干','stem'=>5,'tenGodIndex'=>7],['label'=>'年支（蔵干）','stem'=>5,'tenGodIndex'=>7],['label'=>'月干','stem'=>2,'tenGodIndex'=>4],['label'=>'月支（蔵干）','stem'=>8,'tenGodIndex'=>0],['label'=>'日支（蔵干）','stem'=>0,'tenGodIndex'=>2],['label'=>'時干','stem'=>6,'tenGodIndex'=>8],['label'=>'時支（蔵干）','stem'=>8,'tenGodIndex'=>0]],'tenchusatsuBranches'=>[4,5],'daiyun'=>['forward'=>true,'startAge'=>1,'periods'=>[['stem'=>3,'branch'=>1,'startAge'=>1,'tenGodIndex'=>5,'juniName'=>'衰'],['stem'=>4,'branch'=>2,'startAge'=>11,'tenGodIndex'=>6,'juniName'=>'病'],['stem'=>5,'branch'=>3,'startAge'=>21,'tenGodIndex'=>7,'juniName'=>'死'],['stem'=>6,'branch'=>4,'startAge'=>31,'tenGodIndex'=>8,'juniName'=>'墓'],['stem'=>7,'branch'=>5,'startAge'=>41,'tenGodIndex'=>9,'juniName'=>'絶'],['stem'=>8,'branch'=>6,'startAge'=>51,'tenGodIndex'=>0,'juniName'=>'胎'],['stem'=>9,'branch'=>7,'startAge'=>61,'tenGodIndex'=>1,'juniName'=>'養'],['stem'=>0,'branch'=>8,'startAge'=>71,'tenGodIndex'=>2,'juniName'=>'長生']]]]],
    ],

    // signIndex/innerTypeIndexの境界ケース。timeZoneCodeは比較に無関係のため'U'固定。
    'seiza_zodiac' => [
        ['input' => ['month'=>1,'day'=>20], 'expected' => ['signIndex'=>1,'innerTypeIndex'=>3]],
        ['input' => ['month'=>2,'day'=>19], 'expected' => ['signIndex'=>2,'innerTypeIndex'=>9]],
        ['input' => ['month'=>3,'day'=>21], 'expected' => ['signIndex'=>3,'innerTypeIndex'=>6]],
        ['input' => ['month'=>4,'day'=>20], 'expected' => ['signIndex'=>4,'innerTypeIndex'=>0]],
        ['input' => ['month'=>5,'day'=>21], 'expected' => ['signIndex'=>5,'innerTypeIndex'=>8]],
        ['input' => ['month'=>6,'day'=>22], 'expected' => ['signIndex'=>6,'innerTypeIndex'=>4]],
        ['input' => ['month'=>7,'day'=>23], 'expected' => ['signIndex'=>7,'innerTypeIndex'=>0]],
        ['input' => ['month'=>8,'day'=>23], 'expected' => ['signIndex'=>8,'innerTypeIndex'=>7]],
        ['input' => ['month'=>9,'day'=>23], 'expected' => ['signIndex'=>9,'innerTypeIndex'=>2]],
        ['input' => ['month'=>10,'day'=>24], 'expected' => ['signIndex'=>10,'innerTypeIndex'=>10]],
        ['input' => ['month'=>11,'day'=>22], 'expected' => ['signIndex'=>11,'innerTypeIndex'=>3]],
        ['input' => ['month'=>12,'day'=>22], 'expected' => ['signIndex'=>0,'innerTypeIndex'=>10]],
        ['input' => ['month'=>12,'day'=>21], 'expected' => ['signIndex'=>11,'innerTypeIndex'=>9]],
        ['input' => ['month'=>1,'day'=>19], 'expected' => ['signIndex'=>0,'innerTypeIndex'=>2]],
        ['input' => ['month'=>7,'day'=>22], 'expected' => ['signIndex'=>6,'innerTypeIndex'=>11]],
    ],

    // timeZoneIndexは月日と無関係の純粋なコード→インデックス変換。
    'seiza_timezone' => [
        ['input' => ['timeZoneCode'=>'M'], 'expected' => ['timeZoneIndex'=>0]],
        ['input' => ['timeZoneCode'=>'D'], 'expected' => ['timeZoneIndex'=>1]],
        ['input' => ['timeZoneCode'=>'N'], 'expected' => ['timeZoneIndex'=>2]],
        ['input' => ['timeZoneCode'=>'L'], 'expected' => ['timeZoneIndex'=>3]],
        ['input' => ['timeZoneCode'=>'U'], 'expected' => ['timeZoneIndex'=>4]],
    ],
];
