?php
declare(strict_types=1);
require_once __DIR__ . '/../../../inc/auto-link.php';
ob_start();
?>
<!DOCTYPE html>
<html lang="ja">
<head>
  <script async src="https://www.googletagmanager.com/gtag/js?id=G-P1EKB3WWX8"></script>
  <script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','G-P1EKB3WWX8');</script>
  <meta charset="UTF-8">
  <link rel="canonical" href="https://life-fun.net/articles/tarot/temperance/" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="タロット「節制（TEMPERANCE）」の意味を徹底解説。正位置・逆位置それぞれの恋愛・仕事・人間関係への影響と、カードが伝えるメッセージをわかりやすく紹介します。">
  <title>節制（TEMPERANCE）タロットの意味｜正位置・逆位置・恋愛・仕事を解説</title>
  <link rel="icon" type="image/png" href="/favicon.png"><link rel="apple-touch-icon" href="/favicon.png">
  <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-6979913482925873" crossorigin="anonymous"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Shippori+Mincho:wght@400;500;600;700&family=Zen+Kaku+Gothic+New:wght@300;400;500&family=DM+Mono:wght@300;400&display=swap" rel="stylesheet">
  <style>
  *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}:root{--ff-serif:'Shippori Mincho',serif;--ff-sans:'Zen Kaku Gothic New',sans-serif;--ff-mono:'DM Mono',monospace;--accent:#7c4dce;--accent-lt:#9b72ef;--gold:#c9a84c;--text:#1a1a2e;--muted:#6b6b8a;--border:#e5e3ee;--bg:#faf7ff;--bg2:#f8f7fc;}
  html{font-size:16px;scroll-behavior:smooth}body{background:var(--bg);color:var(--text);font-family:var(--ff-sans);font-weight:400;line-height:1.85}
  .art-header{background:#fff;border-bottom:1px solid var(--border);position:sticky;top:0;z-index:100}.art-header-inner{max-width:780px;margin:0 auto;padding:0 1.2rem;display:flex;align-items:center;justify-content:space-between;height:52px}.art-logo{font-family:var(--ff-serif);font-size:1rem;font-weight:700;color:var(--text);text-decoration:none}.art-logo em{font-style:italic;color:var(--gold)}.art-back{font-family:var(--ff-mono);font-size:.7rem;color:var(--muted);text-decoration:none;border:1px solid var(--border);padding:.25rem .75rem;border-radius:20px;transition:border-color .2s,color .2s}.art-back:hover{border-color:var(--accent-lt);color:var(--accent)}
  .wrap{max-width:780px;margin:0 auto;padding:0 1.2rem}.breadcrumb{font-size:.72rem;color:var(--muted);padding:1rem 0 0;font-family:var(--ff-mono);letter-spacing:.04em}.breadcrumb a{color:var(--muted);text-decoration:none}.breadcrumb a:hover{color:var(--accent)}.breadcrumb span{margin:0 .4rem}
  .art-hero{padding:2rem 0 1.5rem;border-bottom:1px solid var(--border);display:flex;gap:2rem;align-items:flex-start}.art-hero-text{flex:1}.art-label{font-family:var(--ff-mono);font-size:.65rem;letter-spacing:.2em;color:var(--accent);text-transform:uppercase;margin-bottom:.75rem;display:block}.art-hero h1{font-family:var(--ff-serif);font-size:clamp(1.4rem,4vw,2rem);font-weight:700;line-height:1.3;letter-spacing:.04em;color:var(--text);margin-bottom:.75rem}.art-lead{font-size:.93rem;color:var(--muted);line-height:1.9}
  .card-visual{width:120px;flex-shrink:0;background:linear-gradient(170deg,#1e0e42 0%,#0d051f 100%);border:2px solid var(--gold);border-radius:10px;padding:.7rem .6rem .8rem;text-align:center;position:relative;box-shadow:0 0 0 1px rgba(201,168,76,.15),0 8px 32px rgba(0,0,0,.5),inset 0 0 20px rgba(155,114,239,.15);display:flex;flex-direction:column;align-items:center;}.card-visual::before,.card-visual::after{content:'';position:absolute;width:10px;height:10px;border:1.5px solid var(--gold);opacity:.7;}.card-visual::before{top:5px;left:5px;border-right:none;border-bottom:none}.card-visual::after{bottom:5px;right:5px;border-left:none;border-top:none}.card-roman{font-family:var(--ff-mono);font-size:.65rem;letter-spacing:.2em;color:rgba(201,168,76,.8);margin-bottom:.5rem;}.card-illust{width:84px;height:84px;border:none;border-radius:3px;background:transparent;display:flex;align-items:center;justify-content:center;font-size:2.6rem;line-height:1;margin-bottom:.6rem;position:relative;overflow:hidden;}.card-illust img{width:100%;height:100%;object-fit:contain;display:block}.card-en{font-family:var(--ff-mono);font-size:.5rem;letter-spacing:.18em;color:rgba(201,168,76,.75);text-transform:uppercase;margin-bottom:.25rem;}.card-ja{font-family:var(--ff-serif);font-size:.85rem;font-weight:700;color:#e8e0ff}
  .kw-tags{display:flex;flex-wrap:wrap;gap:.4rem;margin:1.2rem 0}.kw-tag{font-family:var(--ff-mono);font-size:.7rem;padding:.25rem .7rem;border-radius:20px;border:1px solid var(--border);color:var(--muted);background:#fff}.kw-tag.upright{border-color:rgba(124,77,206,.3);color:var(--accent);background:rgba(124,77,206,.05)}.kw-tag.reversed{border-color:rgba(180,100,80,.3);color:#a05040;background:rgba(180,100,80,.05)}
  .cta-box{background:linear-gradient(135deg,#f5f0ff 0%,#fdf4fa 100%);border:1px solid #d4bfff;border-radius:12px;padding:1.25rem 1.5rem;margin:1.5rem 0;display:flex;align-items:center;justify-content:space-between;gap:1rem;flex-wrap:wrap}.cta-box p{font-size:.9rem;color:var(--text);font-weight:500}.cta-box small{display:block;font-size:.78rem;color:var(--muted);margin-top:.2rem;font-weight:400}.cta-btn{display:inline-block;background:var(--accent);color:#fff;font-family:var(--ff-sans);font-size:.85rem;font-weight:500;padding:.65rem 1.5rem;border-radius:24px;text-decoration:none;white-space:nowrap;transition:background .2s,transform .15s}.cta-btn:hover{background:var(--accent-lt);transform:translateY(-1px)}
  .toc{background:var(--bg2);border:1px solid var(--border);border-radius:10px;padding:1.25rem 1.5rem;margin:2rem 0}.toc-title{font-size:.8rem;font-weight:500;color:var(--muted);letter-spacing:.1em;margin-bottom:.75rem;font-family:var(--ff-mono)}.toc ol{padding-left:1.2rem;display:flex;flex-direction:column;gap:.35rem}.toc li{font-size:.88rem}.toc a{color:var(--accent);text-decoration:none}.toc a:hover{text-decoration:underline}
  .art-section{padding:2.5rem 0;border-bottom:1px solid var(--border)}.art-section:last-child{border-bottom:none}.art-section h2{font-family:var(--ff-serif);font-size:1.35rem;font-weight:700;color:var(--text);margin-bottom:1rem;padding-left:.9rem;border-left:3px solid var(--accent)}.art-section p{font-size:.93rem;line-height:1.9;color:#333;margin-bottom:.9rem}.art-section p:last-child{margin-bottom:0}
  .reading-box{border-radius:10px;padding:1.2rem 1.4rem;margin:1rem 0}.reading-box.upright{background:rgba(124,77,206,.06);border:1px solid rgba(124,77,206,.2)}.reading-box.reversed{background:rgba(180,100,80,.05);border:1px solid rgba(180,100,80,.2)}.reading-box-label{font-family:var(--ff-mono);font-size:.65rem;letter-spacing:.15em;margin-bottom:.6rem;font-weight:500}.reading-box.upright .reading-box-label{color:var(--accent)}.reading-box.reversed .reading-box-label{color:#a05040}.reading-box p{font-size:.92rem;line-height:1.9;color:#333;margin-bottom:.7rem}.reading-box p:last-child{margin-bottom:0}
  .cat-grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin-top:1rem}.cat-card{border-radius:10px;padding:1rem 1.1rem;border:1px solid var(--border);background:#fff}.cat-label{font-family:var(--ff-mono);font-size:.65rem;letter-spacing:.12em;color:var(--muted);margin-bottom:.4rem}.cat-text{font-size:.88rem;line-height:1.75;color:#333}
  .faq-list{display:flex;flex-direction:column;gap:.75rem;margin-top:1rem}.faq-item{border:1px solid var(--border);border-radius:10px;overflow:hidden}.faq-q{font-size:.9rem;font-weight:500;padding:.9rem 1.1rem;background:var(--bg2);cursor:pointer;display:flex;align-items:center;justify-content:space-between;gap:.5rem}.faq-q::after{content:'＋';font-family:var(--ff-mono);color:var(--accent);flex-shrink:0;transition:transform .2s}.faq-item.open .faq-q::after{transform:rotate(45deg)}.faq-a{font-size:.88rem;color:#444;line-height:1.85;padding:0 1.1rem;max-height:0;overflow:hidden;transition:max-height .35s ease,padding .35s ease}.faq-item.open .faq-a{max-height:400px;padding:.9rem 1.1rem}
  .card-nav{display:flex;gap:.75rem;margin-top:1rem;flex-wrap:wrap}.card-nav-item{flex:1;min-width:140px;background:var(--bg2);border:1px solid var(--border);border-radius:10px;padding:.9rem 1rem;text-decoration:none;display:block;transition:border-color .2s,transform .15s}.card-nav-item:hover{border-color:var(--accent-lt);transform:translateY(-2px)}.card-nav-dir{font-size:.65rem;color:var(--muted);font-family:var(--ff-mono);margin-bottom:.3rem}.card-nav-name{font-size:.9rem;font-weight:500;color:var(--accent)}
  .related-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:.75rem;margin-top:1rem}.related-card{background:var(--bg2);border:1px solid var(--border);border-radius:10px;padding:.9rem 1rem;text-decoration:none;display:block;transition:border-color .2s,transform .15s}.related-card:hover{border-color:var(--accent-lt);transform:translateY(-2px)}.related-card-label{font-size:.7rem;color:var(--muted);margin-bottom:.3rem;font-family:var(--ff-mono)}.related-card-title{font-size:.9rem;font-weight:500;color:var(--accent)}
  @media(max-width:600px){.art-hero{flex-direction:column-reverse;gap:1.5rem;align-items:center}.card-visual{width:130px}.cat-grid{grid-template-columns:1fr}.cta-box{flex-direction:column;align-items:flex-start}}.al-link{color:var(--accent);text-decoration:underline;text-decoration-style:dotted;text-underline-offset:3px;transition:color .2s}.al-link:hover{color:var(--accent-lt)}
  </style>
  <script type="application/ld+json">{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":"節制は禁欲を意味するカード？","acceptedAnswer":{"@type":"Answer","text":"禁欲ではなく「ちょうどよさ」の象徴です。どちらかに偏らず中庸を取ることが吉とされます。足すことも引くことも、バランスが大切です。"}},{"@type":"Question","name":"節制が恋愛で出たら？","acceptedAnswer":{"@type":"Answer","text":"お互いのペースを大切にした穏やかな関係を示します。焦りは禁物。二人のリズムを尊重することが、長続きする関係の秘訣です。"}},{"@type":"Question","name":"節制の逆位置は何を示す？","acceptedAnswer":{"@type":"Answer","text":"過剰・不均衡・焦りのサインです。どこかで無理が生じている時期。燃え尽きる前に気づいてください。"}}]}</script>
  <script type="application/ld+json">{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"占いPortal","item":"https://life-fun.net/"},{"@type":"ListItem","position":2,"name":"タロット占い","item":"https://life-fun.net/tarot"},{"@type":"ListItem","position":3,"name":"タロット解説","item":"https://life-fun.net/articles/tarot/"},{"@type":"ListItem","position":4,"name":"節制（TEMPERANCE）","item":"https://life-fun.net/articles/tarot/temperance/"}]}</script>
</head>
<body>
<header class="art-header"><div class="art-header-inner"><a href="/" class="art-logo">占い<em>Portal</em></a><a href="/tarot" class="art-back">🔮 タロットを占う →</a></div></header>
<div class="wrap">
  <nav class="breadcrumb"><a href="/">占いPortal</a><span>›</span><a href="/articles/tarot/">タロット解説</a><span>›</span>節制（TEMPERANCE）</nav>
  <div class="art-hero"><div class="art-hero-text"><span class="art-label">TAROT · 大アルカナ XIV</span><h1>節制（TEMPERANCE）<br>タロットの意味・正位置・逆位置</h1><p class="art-lead">大アルカナ14番「節制」は、二つの杯の間で水を注ぐ天使のカードです。過剰でも不足でもなく、ちょうどいいを探す旅。急ぎすぎず、焦らず——このカードは「中庸」という最も難しい智慧を教えます。</p><div class="kw-tags"><span class="kw-tag upright">調和</span><span class="kw-tag upright">バランス</span><span class="kw-tag upright">忍耐</span><span class="kw-tag upright">癒し</span><span class="kw-tag upright">中庸</span> <span class="kw-tag reversed">不均衡</span><span class="kw-tag reversed">過剰</span><span class="kw-tag reversed">焦り</span></div></div><div class="card-visual"><div class="card-roman">XIV</div><div class="card-illust"><img src="/cards/temperance.png" alt="節制"></div><div class="card-en">TEMPERANCE</div><div class="card-ja">節制</div></div></div>
  <div class="cta-box"><div><p>🔮 今すぐカードを引いてみる</p><small>。</small></div><a href="/tarot" class="cta-btn">タロット占いを始める →</a></div>
  <nav class="toc"><p class="toc-title">目次</p><ol><li><a href="#overview"></a></li><li><a href="#upright">正位置の意味</a></li><li><a href="#reversed">逆位置の意味</a></li><li><a href="#love">恋愛での意味</a></li><li><a href="#work">仕事・お金での意味</a></li><li><a href="#faq">よくある質問</a></li></ol></nav>
  <section class="art-section" id="overview"><h2></h2><p>天使は一方の杯から他方の杯へと、水を静かに注いでいます。片足は陸に、もう片足は水の中に。天界と地上の間に立ちながら、完璧なバランスを保っています。このカードが示すのは「完璧さ」ではなく「動的なバランス」——状況に合わせて常に調整し続ける、生きたバランス感覚です。</p></section>
  <section class="art-section" id="upright"><h2>正位置の意味</h2><div class="reading-box upright"><div class="reading-box-label">UPRIGHT · 正位置</div><p>今は急がず着実に進む時です。バランスを保つことが最も賢い選択。一歩一歩を丁寧に踏みしめることで、確実に前に進めます。焦りを手放してください。今のペースが正しいです。</p></div></section>
  <section class="art-section" id="reversed"><h2>逆位置の意味</h2><div class="reading-box reversed"><div class="reading-box-label">REVERSED · 逆位置</div><p>どこかで過剰になっている状態です。仕事・感情・欲求のいずれかが暴走しています。今一番「やりすぎている」ことを一つ見つけて、意識的に減らしてみてください。</p></div></section>
  <section class="art-section" id="love"><h2>恋愛での意味</h2><div class="cat-grid"><div class="cat-card"><div class="cat-label">UPRIGHT · 正位置</div><div class="cat-text">お互いのペースを尊重した穏やかな関係が育まれます。押したり引いたりせず、二人のリズムを大切にする時期です。</div></div><div class="cat-card"><div class="cat-label">REVERSED · 逆位置</div><div class="cat-text">片方に負担が偏っているか、ペースが合わない状態です。どちらかが無理をしているなら、それを正直に話し合う機会を作ってください。</div></div></div></section>
  <section class="art-section" id="work"><h2>仕事・お金での意味</h2><div class="cat-grid"><div class="cat-card"><div class="cat-label">UPRIGHT · 仕事</div><div class="cat-text">コツコツとした積み上げが評価される時期です。無理のないペースが長期的成功をもたらします。急がば回れの精神で。</div></div><div class="cat-card"><div class="cat-label">REVERSED · 仕事</div><div class="cat-text">仕事量・責任のバランスが崩れています。燃え尽きる前に、意識的に休む時間を作ってください。</div></div><div class="cat-card"><div class="cat-label">UPRIGHT · 金運</div><div class="cat-text">堅実な家計管理が吉です。収入と支出のバランスを見直す時。少しずつでも着実に積み上げることが今の金運の鍵です。</div></div><div class="cat-card"><div class="cat-label">REVERSED · 金運</div><div class="cat-text">散財・借金・収支のアンバランスへの警告です。感情的な消費パターンを見直す必要があります。</div></div></div></section>
  <section class="art-section" id="faq"><h2>よくある質問</h2><div class="faq-list"><div class="faq-item"><div class="faq-q" onclick="toggleFaq(this)">節制は禁欲を意味するカード？</div><div class="faq-a">禁欲ではなく「ちょうどよさ」の象徴です。どちらかに偏らず中庸を取ることが吉とされます。足すことも引くことも、バランスが大切です。</div></div><div class="faq-item"><div class="faq-q" onclick="toggleFaq(this)">節制が恋愛で出たら？</div><div class="faq-a">お互いのペースを大切にした穏やかな関係を示します。焦りは禁物。二人のリズムを尊重することが、長続きする関係の秘訣です。</div></div><div class="faq-item"><div class="faq-q" onclick="toggleFaq(this)">節制の逆位置は何を示す？</div><div class="faq-a">過剰・不均衡・焦りのサインです。どこかで無理が生じている時期。燃え尽きる前に気づいてください。</div></div></div></section>
  <section class="art-section"><h2>他のカードを見る</h2><div class="card-nav"><a href="/articles/tarot/death/" class="card-nav-item"><div class="card-nav-dir">← 前のカード</div><div class="card-nav-name">死神</div></a><a href="/articles/tarot/devil/" class="card-nav-item"><div class="card-nav-dir">次のカード →</div><div class="card-nav-name">悪魔</div></a></div></section>
  <section class="art-section"><h2>関連コンテンツ</h2><div class="related-grid"><a href="/tarot" class="related-card"><div class="related-card-label">タロット占い</div><div class="related-card-title">実際にカードを引いてみる →</div></a><a href="/articles/tarot/" class="related-card"><div class="related-card-label">タロット完全ガイド</div><div class="related-card-title">大アルカナの基礎知識を学ぶ →</div></a><a href="/" class="related-card"><div class="related-card-label">三星統合鑑定</div><div class="related-card-title">タロット×星座×数秘で深読みする →</div></a><a href="/numerology" class="related-card"><div class="related-card-label">数秘術</div><div class="related-card-title">誕生日から運命数を読み解く →</div></a></div></section>
</div>
<script>function toggleFaq(el){const item=el.parentElement;item.classList.toggle('open');}</script>
<?php $currentSlug='tarot'; $pageType='article'; require __DIR__.'/../../../inc/footer.php'; ?>
</body>
</html>
<?php $html=ob_get_clean();echo autoLink($html,'tarot'); ?>